package nju.sec.yz.ExpressSystem.presentation.controlerui;

public enum AccountControl {
	ACCOUNT_MAIN,
	INCOME,
	INITIAL,CHECK_INITIAL,
	COST,COST_SUCCESS,
	TABLE_OPERATE,TABLE_COST,
	ADD_ACCOUNT,ADD_SUCCESS,
	DELETE_ACCOUNT,
	MODIFY_ACCOUNTLIST,MODIFY,MODIFY_SUCCESS,
	ENQUIRY_ACCOUNT,
	LOG_CHECK;
	
}
