package nju.sec.yz.ExpressSystem.presentation.controlerui;

public enum INVENTORY_CONTROL {
	INVENTORY_MAIN,
	INVENTORY_IN,IN_SUCCESS,
	INVENTORY_OUT,OUT_SUCCESS,
	INVENTORY_OBSERVE,
	INVENTORY_CHECK,
	INVENTORY_SET,SET_SUCCESS;
}
