package nju.sec.yz.ExpressSystem.presentation.controlerui;

public enum MAIN_CONTROL {
	LOGIN,DELIVERY_ENQUIRY,DELIVER,POSITION,TRANSITER,INVENTORY,SENIOR_ACCOUNTANCY,JUNIOR_ACCOUNTANCY,MANAGER,ADMINSTRATER;
}
