package nju.sec.yz.ExpressSystem.presentation.controlerui;

public enum ManagerControl {
	MANAGER_MAIN,
	AGENCY_ADD,AGENCY_ADD_SUCCESS,
	AGENCY_DELETE,
	AGENCY_MODIFY,AGENCY_LIST,AGENCY_MODIFY_SUCCESS,
	AGENCY_INQUIRY,
	STAFF_ADD,STAFF_ADD_SUCCESS,
	STAFF_DELETE,
	STAFF_MODIFY,STAFF_LIST,STAFF_MODIFY_SUCCESS,
	STAFF_INQUIRY,
	SALARY_MODIFY,
	SALARY_INQUIRY,
	CONST_ADD,CONST_ADD_SUCCESS,
	CONST_MODIFY,CONST_MODIFY_SUCCESS,
	CONST_INQUIRY,
	RECEIPT_LIST,
	RECEIPT_MODIFY,
	ACCOUNT_CHECK,COST_CHECK,OPERATE_CHECK,
	LOG_CHECK;
}
