package nju.sec.yz.ExpressSystem.presentation.controlerui;

public enum POSITION_CONTROL {
	POSITION_MAIN,
	ARRIVE,
	DELIVE,
	GETPAY,
	CAR_ADD,
	CAR_DELETE,
	CAR_MODIFY,CAR_MODIFY2,
	CAR_INQUIRY,
	DRIVER_ADD,
	DRIVER_DELETE,
	DRIVER_MODIFY,
	DRIVER_INQUIRY,
	LOAD,LOAD_SUCCESS;
}
