package nju.sec.yz.ExpressSystem.presentation.controlerui;

public enum POSITION_CONTROL {
	POSITION_MAIN,
	ARRIVE,ARRIVE_SUCCESS,
	DELIVE,DELIVE_SUCCESS,
	GETPAY,
	CAR_ADD,CAR_ADD_SUCCESS,
	CAR_DELETE,
	CAR_MODIFY,CAR_MODIFY_SUCCESS,
	CAR_INQUIRY,
	DRIVER_ADD,DRIVER_ADD_SUCCESS,
	DRIVER_DELETE,
	DRIVER_MODIFY,DRIVER_MODIFY_SUCCESS,
	DRIVER_INQUIRY,
	LOAD,LOAD_SUCCESS;
}
