package nju.sec.yz.ExpressSystem.presentation.controlerui;

public enum TransitControl {
	TRANSIT_MAIN,
	FLIGHT_LOAD,FLIGHT_LOAD_SUCCESS,
	TRAIN_LOAD,TRAON_LOAD_SUCCESS,
	CAR_LOAD,CAR_LOAD_SUCCESS,
	TRANSIT,TRANSIT_SUCCESS,
	ARRIVE,ARRIVE_SUCCESS;
}
